### ISSUE TITLE
Flipcard element does not open when clicked in YOOtheme builder

### ISSUE THREAD

**Issue by griffinskatzcy** [forrestkirby/flipcard-element#16]
Hi. I've installed your custom element, but I'm not able to select it in the YOOtheme Pro Page Builder (I get a JavaScript error)

1. Open the page/post in WordPress and access the Yootheme page builder
2. Scroll down and click on the "HD Flipcard" element.
3. See the Javascript error (pasted below) in the dev tools console.

On our site, we have the following installed:
WordPress Version 5.6
YOOtheme Version: 2.0.8

Is this extension not compatible with version 2.0.8 of YOOtheme? Thank you in advance!

TypeError: Cannot use 'in' operator to search for 'default' in null
    at customizer.min.js?ver=2.0.8:13
    at customizer.min.js?ver=2.0.8:13
    at e.a (customizer.min.js?ver=2.0.8:13)
    at customizer.min.js?ver=2.0.8:13
    at e.a (customizer.min.js?ver=2.0.8:13)
    at On.make (customizer.min.js?ver=2.0.8:13)
    at click (customizer.min.js?ver=2.0.8:13)
    at Wt (customizer.min.js?ver=2.0.8:13)
    at HTMLAnchorElement.n (customizer.min.js?ver=2.0.8:13)
    at HTMLAnchorElement.Cr.o._wrapper (customizer.min.js?ver=2.0.8:13)
Vt @ customizer.min.js?ver=2.0.8:13
Ut @ customizer.min.js?ver=2.0.8:13
Ht @ customizer.min.js?ver=2.0.8:13
Wt @ customizer.min.js?ver=2.0.8:13
n @ customizer.min.js?ver=2.0.8:13
Cr.o._wrapper @ customizer.min.js?ver=2.0.8:13

 - OS: Windows 10
 - Browser: Chrome
 - Version 87.0.4280.88

**Comment by forrestkirby** [comment]
Hi griffinskatzcy,

the master branch is always kept up to date so that it is compatible with the latest version of YOOtheme Pro. Compatibility with older versions cannot be guaranteed due to breaking changes introduced by a new version of YOOtheme Pro. It is generally recommended to keep both YOOtheme Pro and the extensions up to date.

That being said, you can use an older version of this element which is compatible with the version of YOOtheme Pro you have currently installed. Simply browse the [commit history](https://github.com/forrestkirby/flipcard-element/commits/master) for the version you need. In your case, [2.0.5](https://github.com/forrestkirby/flipcard-element/tree/6ee693d11eec05c04baf1ddf5ab4abbb5f54400d) should be fine.

Kind regards
Thomas

**Comment by griffinskatzcy** [comment]
Hi Thomas,

Thank you very much for your reply and this information. I'm new to GitHub and did not realize how to obtain an earlier version of the element. I replaced the current version with version 2.0.5 and it works great now. Thank you so much!

Best regards,
Sean
