### ISSUE TITLE
Multiple dynamic items

### ISSUE THREAD

**Issue by webfoolery** [forrestkirby/flipcard-element#24]
Hi there.

Thank you for developing & sharing this extension. Do you have any plans to make it support multiple dynamic content? Unless I'm missing something the element currently allows only single dynamic items. In that regard it currently can't be pointed at a category of articles to show them all, and an item has to be created for each article. Other dynamic elements (like Grid) handle multiple dynamic items.

Thanks again.

**Comment by forrestkirby** [comment]
Hi webfoolery,

you are right, this is not possible with this element. You can only use the dynamic content *Start* option to show multiple items and this will require adding multiple flipcard elements while the total number will be limited, as you already said. This is because this element is initially based on the Panel element which is a basic element, too. I don’t have any plans to change the element type from a basic element to a multiple items element at the moment, I’m sorry. It’d be worth considering to create a separate element instead of changing the current element (similar to what the Grid element is to the Panel element), but I don’t have any plans to do so either.

Best regards
